VERIFY_TARGET=testMbedtlsVerify
SIGN_TARGET=testMbedtlsSign
MBEDTLS_DIR=mbedtls/library
MBEDTLS_LIB_NAME=mbedcrypto
MBEDTLS_LIB=$(MBEDTLS_DIR)/lib$(MBEDTLS_LIB_NAME).a
MBEDTLS_INC=mbedtls/include

VERIFY_SRC = \
    verify.c

SIGN_SRC = \
	sign.c

all: $(VERIFY_TARGET) #$(SIGN_TARGET)

.PHONY: $(MBEDTLS_LIB_NAME)

$(VERIFY_TARGET): $(VERIFY_SRC) $(MBEDTLS_LIB)
	$(CC) -o $@ $(VERIFY_SRC) -L$(MBEDTLS_DIR) -l$(MBEDTLS_LIB_NAME) -I$(MBEDTLS_INC)

$(SIGN_TARGET): $(SIGN_SRC) $(MBEDTLS_LIB)
	$(CC) -o $@ $(SIGN_SRC) -L$(MBEDTLS_DIR) -l$(MBEDTLS_LIB_NAME) -I$(MBEDTLS_INC)

$(MBEDTLS_LIB): $(MBEDTLS_LIB_NAME)
	$(MAKE) -C $(MBEDTLS_DIR)